apiVersion: v1
kind: LimitRange
metadata:
  name: container-defaults
  namespace: {{ include "cost-guardrails.namespace" . }}
  labels:
    {{- include "cost-guardrails.labels" . | nindent 4 }}
spec:
  limits:
    - type: Container
      default:
        cpu: {{ .Values.limitRange.defaultLimitCpu | quote }}
        memory: {{ .Values.limitRange.defaultLimitMemory | quote }}
      defaultRequest:
        cpu: {{ .Values.limitRange.defaultRequestCpu | quote }}
        memory: {{ .Values.limitRange.defaultRequestMemory | quote }}
      max:
        cpu: {{ .Values.limitRange.maxCpu | quote }}
        memory: {{ .Values.limitRange.maxMemory | quote }}
